# Generated by Django 5.0.6 on 2024-05-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_post_image_id_post_excerpt_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
