# Generated by Django 5.0.6 on 2024-05-21 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_category_post_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
