# Generated by Django 5.0.6 on 2024-05-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_post_albums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='albums',
        ),
    ]
